name: Deploy and Test with TestDriver.ai

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    outputs:
      vercel_url: ${{ steps.vercel-deployment.outputs.preview-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        id: vercel-deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  test:
    name: Run TestDriver.ai Tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Vercel URL 
        run: echo "VERCEL_URL=${{ needs.deploy.outputs.vercel_url }}"

      - name: Run TestDriver.ai
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prerun: |
            cd $env:TEMP
            npm install dashcam-chrome
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ needs.deploy.outputs.vercel_url }}"
            Start-Sleep -Seconds 5
          prompt: |
            1. /run testdriver/test.yml
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTDRIVER_API_KEY: ${{ secrets.TESTDRIVER_API_KEY }}
          
