name: Deploy and Test with TestDriver.ai

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Save Vercel Deployment URL
        id: deployment
        run: echo "VERCEL_URL=$(cat .vercel/output.json | jq -r '.url')" >> $GITHUB_ENV

  test:
    name: Run TestDriver.ai Tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TestDriver.ai
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. Open Google Chrome
            2. Navigate to ${{ env.VERCEL_URL }}
            3. Perform tests on the deployed site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTDRIVER_API_KEY: ${{ secrets.TESTDRIVER_API_KEY }}
          