name: Deploy and Test with TestDriver.ai

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        id: vercel-deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Save Vercel Deployment URL
        run: echo "VERCEL_URL=${{ steps.vercel-deployment.outputs.preview-url }}" >> $GITHUB_ENV


  test:
    name: Run TestDriver.ai Tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo " VERCEL_URL=${{ env.VERCEL_URL }}"

      - name: Run TestDriver.ai
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prerun: |
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "${{ env.VERCEL_URL }}"
            Start-Sleep -Seconds 5
          prompt: |
            /run testdriver/test.yml
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTDRIVER_API_KEY: ${{ secrets.TESTDRIVER_API_KEY }}
          